version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:rw
    command: sleep infinity
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=host.docker.internal:0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
